[package]
name = "tar_ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar_ecs_macros = { path = "macros" }
fxhash = "0.2"
