[package]
name = "tar_shader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-gltf = "1"
wgpu = "0.15"
bytemuck = "1.13.1"

[build-dependencies]
wgsl_to_wgpu = "0.3.1"
