[package]
name = "tar_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
bytemuck = { version = "1.13", features = ["derive"] }
tar_shader = { path = "../tar_shader" }
