[package]
name = "scr_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scr_types = {path = "../scr_types/"}
tar_ecs = {path = "../tar_ecs"}
