[package]
name = "tar_abi"
version = "0.1.0"
edition = "2021"

[dependencies]
scr_types = { path = "../scr_types" }
libloading = "0.8.0"
fs_extra = "1.3"
uuid = "1"
quote = "1"
syn = "2"
prettyplease = "0.2.6"
proc-macro2 = "1"
toml = "0.7"
