[package]
name = "tar_scripting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.139"
libloading = "0.7.4"
ron = "0.8"
serde = {version = "1", features = ["derive"]}