[package]
name = "tar_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.21.0"
tar_types = { path = "../tar_types" }
egui_file = "0.8.0"
uuid = { version = "1.3.0", features = ["v4"] }
