[package]
name = "tar_entry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar_ecs = {path="../tar_ecs"}
tar_gui = {path="../tar_gui"}
tokio = {version = "1", features=["full"]}