[package]
name = "tar_entry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar_core = { path = "../tar_core" }
tokio = { version = "1", features = ["full"] }
tar_abi = { path = "../tar_abi" }
