[package]
name = "tar_render"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = "1"
bytemuck = { version = "1.12.1", features = ["derive"] }
cgmath = "0.18"
env_logger = "0.10.0"
pollster = "0.3.0"
log = "0.4.17"
tobj = { version = "3.2.3", features = ["async"] }
wgpu = { version = "0.15.1" }
winit = "0.28.1"
instant = "0.1.12"
egui = "0.21.0"
thiserror = "1.0"
gltf = "1.0"
tar_res = { path = "../tar_res" }
tar_types = { path = "../tar_types" }
scr_types = { path = "../scr_types" }
async-trait = "0.1.60"
uuid = { version = "1.3.0", features = ["v4"] }
threadpool = "1.8.1"
crossbeam-channel = "0.5.6"

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { version = "0.11.12" }
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
wgpu = { version = "0.15.1", features = ["webgl"] }
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
web-sys = { version = "0.3.60", features = [
    "Document",
    "Window",
    "Element",
    "Location",
] }

[build-dependencies]
anyhow = "1.0.65"
fs_extra = "1.2"
glob = "0.3"
