[package]
name = "tar_render"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = "1"
bytemuck = { version = "1.12.1", features = [ "derive" ] }
cgmath = "0.18"
env_logger = "0.9.1"
pollster = "0.2.5"
log = "0.4.17"
tobj = { version = "3.2.3", features = ["async"]}
wgpu = { version = "0.14"}
winit = "0.27.4"
instant = "0.1.12"
# eframe = {version="0.19.0", features=["wgpu"]}
egui = "0.19"
thiserror = "1.0"
gltf = "1.0"
tar_res = {path = "../tar_res"}

[dependencies.image]
version = "0.24.4"
default-features = false
features = ["png", "jpeg"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { version = "0.11.12" }
console_error_panic_hook = "0.1.7"
console_log = "0.2"
wgpu = { version = "0.14", features = ["webgl"]}
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
web-sys = { version = "0.3.60", features = [
    "Document",
    "Window",
    "Element",
    "Location",
]}

[build-dependencies]
anyhow = "1.0.65"
fs_extra = "1.2"
glob = "0.3"
