[package]
name = "tar_render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28.3"
env_logger = "0.10"
log = "0.4"
# wgpu = "0.15.1"
glam = "0.23.0"
wgsl_to_wgpu = "0.3.1"
